### ISSUE TITLE
some svg files cant change to woff

### ISSUE THREAD

**Issue by xxholly32** [fontello/ttf2woff#10]
Hello !!! first forgive my poor english

Windows 7

i find some svg files which is from more then one vectorgraph  cant change to woff files.

it`s my test project [https://github.com/xxholly32/startNodejs/tree/gh-pages/demo/iconfont-svg-demo](https://github.com/xxholly32/startNodejs/tree/gh-pages/demo/iconfont-svg-demo) 

i get svg form icomoon by three pic demo.(icomoon.svg)

and a single svg(single.svg) ande use gulp-iconfont to change ttf files

here is the trouble
```javascript
E:\ideaworkspace\startNodejs\demo\iconfont-svg-demo\www\fonts>ttf2woff icomoon.t
tf icomoon.woff

C:\Users\xiangxiao3\AppData\Roaming\npm\node_modules\ttf2woff\index.js:168
        throw 'Checksum error in ' + tableEntry.Tag.toString();
        ^
Checksum error in glyf

E:\ideaworkspace\startNodejs\demo\iconfont-svg-demo\www\fonts>ttf2woff single.tt
f single.woff

E:\ideaworkspace\startNodejs\demo\iconfont-svg-demo\www\fonts>
```

maybe is not a question
i am not learn svg deeply
my purpose is that change icomoon.svg to woff file.

ty !!!

**Comment by puzrin** [comment]
Probably source file is broken. Try to create .ttf from .svg via `svg2ttf`, then convert result to woff with `ttf2woff`.
