### ISSUE TITLE
OTS parsing error: wrong font version for PostScript glyph data

### ISSUE THREAD

**Issue by xornor-web** [fontello/ttf2woff#14]
I am converting myRiadPro.ttf to woff file , It is converting but after when i adding this font in html then font not picking by browser . I got a console warning 
CSS:
@font-face {
    font-family: 'Myriad Pro';
    src: url('../fonts/myRiadPro.woff') format('woff');
}
Error on Browser 
> Failed to decode downloaded font: http://site-url/myriadpro-regular.woff
> (index):1 OTS parsing error: wrong font version for PostScript glyph data

woff mimeType is also set in IIS.

**Comment by puzrin** [comment]
Not enough info to investigate. If you enter error text in google, there will be a lot of results by different reasons. To prove problem is in this package, you need narrow it down:

- Try html file from local disk (without webserver at all)
- Try several font formats in fontface (it should fail with woff and succeed with next)
- Try different browsers (that should not be browser-specific issue)

As soon as you provide more details, i will reopen issue.

**Comment by edoardocavazza** [comment]
Hello, I have the same issue.

> Try html file from local disk (without webserver at all)

Done, Chrome still fails to parse the font

> Try several font formats in fontface (it should fail with woff and succeed with next)

Done, Chrome loads the truetype version

> Try different browsers (that should not be browser-specific issue)

Same error in Firefox.

I have also tried to use the converter provided from convert.io using the same ttf source, and that version worked.

How can I help to identify the issue? Do you need more informations?

**Comment by puzrin** [comment]
@edoardocavazza to be honest, i doubt it worth spend time for this package, because woff is outdated. I'd suggest use woff2 via this package https://github.com/fontello/wawoff2.
