### ISSUE TITLE
throw 'Checksum error in ' + String.fromCharCode.apply

### ISSUE THREAD

**Issue by fancydev18** [fontello/ttf2woff#20]
Hi, trying to convert the attach font:
```
$ ttf2woff f.ttf f.woff

/usr/local/lib/node_modules/ttf2woff/index.js:161
        throw 'Checksum error in ' + String.fromCharCode.apply(null, tableEntry.Tag);
        ^
Checksum error in cmap

```

(had to gzip to attach)

The file can be opened fine with GNOME font viewer on linux.
[f.ttf.gz](https://github.com/fontello/ttf2woff/files/7602394/f.ttf.gz)

**Comment by puzrin** [comment]
`can be opened fine with GNOME font viewer` is NOT suitable proof of correctness. Can't say anything without info how you received your ttf file.

I'd suggest to load/save your file with FontForge. Also consider use woff2 instead of woff https://github.com/fontello/wawoff2
