### ISSUE TITLE
TypeError: arr.readUint16BE is not a function

### ISSUE THREAD

**Issue by aXlireza** [fontello/ttf2woff#21]
When I use the module locally, it works just fine, but once I deploy to server, this error pops up
The array is the same in both working and crashing environment, and yet, it crashes on server

**Comment by aXlireza** [comment]
/node_modules/ttf2woff/index.js:112:23

**Comment by puzrin** [comment]
Make sure your nodejs version is fresh enough. If you insist on bug in this package, please provide a minimal reproducible sample to reopen.

**Comment by aXlireza** [comment]
yeah sorry for that, realized there has been a problem with the actual node version on the server which wasn't clear on the interface

**Comment by omridevk** [comment]
@Axoncodes Which version were you using? I am having the same issue no matter which node version I am using.

**Comment by aXlireza** [comment]
I don't remember which version it was back then, the app was running on cpanel with unclear node version(had to properly update the node version in there while somehow).
Are you sure your cpanel node version is up to date?
You can check if the node or npm getting called in terminal(or upgrade) is the same that the cpanel(WHM) node is running
So if the directions are different, and the upgraded node is on the altered node dir, then you should upgrade node through cpanel or tell the host admin to do so

**Comment by omridevk** [comment]
I am running it locally on an M1 Mac and I am getting this error
with these node versions:
v14.20.0
v16.17.0
v18.7.0

**Comment by omridevk** [comment]
all of those fails for the same reason:
```
TypeError: arr.readUint16BE is not a function
```

**Comment by puzrin** [comment]
@omridevk do you run it from CLI or as library?

**Comment by omridevk** [comment]
as a library, I bundle it with a CLI tool I am making (but I am using it as a lbirary)
```
    const filename = `${fontName}.woff`;
    const buffer = Buffer.from(ttf2woff(ttfFontBuffer).buffer);
    await fs.writeFile(path.join(dest, filename), buffer);
    console.log(`${filename} written!`);
    return {
        buffer,
        fileCreated: path.join(dest, filename),
    };
```

**Comment by omridevk** [comment]
also, thanks for the quick response

**Comment by puzrin** [comment]
1. Try to run it from CLI, make sure it's not problem of node on M1.
2. If CLI works, make sure input of library call is `Buffer`, not typed array.

**Comment by omridevk** [comment]
<img width="736" alt="CleanShot 2022-08-20 at 00 18 02@2x" src="https://user-images.githubusercontent.com/9701896/185708529-cc8e42ad-d64d-4705-b5a5-c8f1cdbc02b2.png">

where that's the console.log of the param passed to ```ttf2woff```

**Comment by omridevk** [comment]
(working in the CLI)

**Comment by puzrin** [comment]
See https://github.com/fontello/ttf2woff/blob/master/ttf2woff.js#L77

Probably, you need recast to `Uint8Array`. Something, `Uint8Array` or `Buffer` should work, I don't remember details, this project is very ancient :). Consider [wawoff2](https://github.com/fontello/wawoff2) as more actual.

**Comment by omridevk** [comment]
wawoff also doesn't work on my machine for some strange reason.

**Comment by puzrin** [comment]
I can discuss only concrete samples in appropriate tracker.

**Comment by omridevk** [comment]
let me push the code to a side branch then I can provide steps to reproduce.

**Comment by omridevk** [comment]
```
    const input = fs.readFileSync(file);
    const ttf = new Uint8Array(input);
    const buffer = ttf2woff(input);
```
where input is a ttf file that worked in the CLI.
same error regardless

**Comment by puzrin** [comment]
Try to copy-paste code from CLI source. It's very small and easy to understand.

**Comment by omridevk** [comment]
will do

**Comment by puzrin** [comment]
Just create a minimalistic code, drop everything not-related. For example, problem can be with bundler and so on.

**Comment by omridevk** [comment]
unfortunately same results:
```
let input;
    try {
        input = fs.readFileSync(file);
    } catch (e) {
        process.exit(1);
    }

    const ttf = new Uint8Array(input);
    const woff = ttf2woff(ttf, {});
```
And again, thanks a lot for the help here, good to see israeli open source
I'll try to. thanks, could it be a rollup thing?

**Comment by puzrin** [comment]
Can not comment rollup in advance. The right approach is to split system to smaller parts, until source of problem localized. As you can see, problem is not with M1.

**Comment by omridevk** [comment]
good catch, it was indeed issue with rollup, thank you very very much for your help.
