### ISSUE TITLE
WOFF 2.0

### ISSUE THREAD

**Issue by jonassmedegaard** [fontello/ttf2woff#3]
Please support WOFF 2.0.

...or document more prominently if in fact it is already supported.

(see https://github.com/ananthakumaran/webify/issues/8 for context)

**Comment by backflip** [comment]
Thanks to @nfroidure there is an Emscripten port: https://github.com/nfroidure/ttf2woff2

**Comment by puzrin** [comment]
4 mb size.

**Comment by backflip** [comment]
Well, the user's browser downloading a woff2 font instead of a woff one won't care about the size of the dependency used to generate it. :)

**Comment by puzrin** [comment]
As i said before - it's not interesting for me to use such solutions. This project's criterias are different from business ones.

**Comment by backflip** [comment]
That's certainly correct. I wasn't suggesting to add this to `ttf2woff` but rather documenting it for anyone interested in using it directly.

**Comment by puzrin** [comment]
Ok. I thought such cross-compiled projects are easy to search. But it you think those link will help to someone - no problem.

Also i'm ready to donate 1k$ for hight quality brotli port (~ the same as we did in [pako](https://github.com/nodeca/pako)).

**Comment by nfroidure** [comment]
What you mean per high quality? If you mean a native wrapper, you should look twice, the emscripten is just a fallback for the native wrapper. Give your $1000 to Mozilla ;).

**Comment by puzrin** [comment]
I mean native implementation in JS, not cross-compiled. ~ the same as we did in pako for zlib.

**Comment by nfroidure** [comment]
In that case, i hope someone will do it, not my priority since we've got something working. Any PR doing the job will be merged though.

**Comment by nfroidure** [comment]
Created the issue https://github.com/nfroidure/ttf2woff2/issues/2
