### ISSUE TITLE
Checksum error in name

### ISSUE THREAD

**Issue by alai** [fontello/ttf2woff#4]
ttf2woff hwxh.ttf hwxh.woff

/usr/local/lib/node_modules/ttf2woff/index.js:160
        throw 'Checksum error in ' + tableEntry.Tag;
                                   ^
Checksum error in name

**Comment by mingfang** [comment]
I'm having the exact same problem now.
Is there an option to skill validation of the checksum?

**Comment by puzrin** [comment]
No such option now.
