### ISSUE TITLE
Litte clarification for table alignment

### ISSUE THREAD

**Issue by iconexperience** [fontello/ttf2woff#6]
In <a href="https://github.com/fontello/ttf2woff/blob/master/index.js#L203">ttf2woff/index.js at line 203</a> you seem to be unsure whether the padding should be done with zero bytes. Here is the relavant part from the <a href="http://www.w3.org/TR/WOFF/">woff spec</a> (only in v1.0, missing in v2.0):

<i>Except for padding with a maximum of three <b>null bytes</b> in places where 4-byte alignment of a table length or block offset is specified</i>

There you have it: Using 0 bytes for the padding is correct, you can remove the question mark in the comment.

**Comment by puzrin** [comment]
Could you do PR ? I looked this code many time ago and don't remember details. Or, if nobody cares about couple of bytes, we can just close tichet as not principal.

**Comment by puzrin** [comment]
Closed - timed out, not principal.
