### ISSUE TITLE
Broken npm package

### ISSUE THREAD

**Issue by stcherenkov** [fontello/ttf2woff#9]
Our company mirrors npm registry to closed environment using Sonatype Nexus and some tricky replication. Replication requires `package` folder inside tgz archive to work properly.

Looks like something went wrong during preparation of version 1.3.0: instead of `package` folder it has `fontello-ttf2woff-8e0d929` folder inside — so Nexus can't parse it properly. Could you please update npm package?

Examples:
http://registry.npmjs.org/ttf2woff/-/ttf2woff-1.2.0.tgz — `package` in archive root,
http://registry.npmjs.org/ttf2woff/-/ttf2woff-1.3.0.tgz — archive with issue

**Comment by puzrin** [comment]
I did `npm install ttf2woff` and it works without problems, installing 1.3.0 version. Seems there is nothing to fix.

Probably, you need to update your archive parser.
